/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'sergii' at '1/4/17 10:39 PM' with Gradle 3.2.1
 *
 * @author sergii, @date 1/4/17 10:39 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
